# /docker-compose.yml
version: "3"

volumes:
  local_postgres_data: {}

services:
  web:
    build: ./
    ports:
      - "80"
      - "443"
    volumes:
      - /app
    depends_on:
      - db

  db:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data