# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - listy-list

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_587e719e389c45a4b97f9022d645661c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_35d9179a12924fc6941c42df3b83d3bc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sharifedak12/listy-list:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'listy-list'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_659d1bf29e3d456baba16c8a7e3b20cd }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_587e719e389c45a4b97f9022d645661c }}/sharifedak12/listy-list:${{ github.sha }}'
